### ISSUE TITLE
matching object using ObjectId

### ISSUE THREAD

**Issue by Gorjel** [JamesOsgood/mongodb-grafana#41]
Is there any option to use field of type ObjectId in $match condition?
This workaround works just fine in mongodb console, but in grafana it doesn't return anything:
`db.my_collection.aggregate([{"$match": {"$expr": {"$eq": [{"$toString" : "$_id"}, "5c44a63607e2b70013102f91"]}}},{"$group": {"_id": "$_id", "total": {"$sum":1}}}])`

**Comment by Gorjel** [comment]
got it working using $convert only. In case some faces same problem:
`db.my_collection.aggregate([
    {
        "$match": {
            "$expr": {
                "$eq": [
                    "$_id",
                    {
                        "$convert": {
                            "input": "5c44a63607e2b70013102f91",
                            "to": "objectId"
                        }
                    }
                ]
            }
        }
    },
    { "$group": { "_id": "$_id", "total": { "$sum": 1 } } }
])
`

**Comment by renan-souza** [comment]
Hello! I'd like to share that using the lates

> got it working using $convert only. In case some faces same problem: `db.my_collection.aggregate([ { "$match": { "$expr": { "$eq": [ "$_id", { "$convert": { "input": "5c44a63607e2b70013102f91", "to": "objectId" } } ] } } }, { "$group": { "_id": "$_id", "total": { "$sum": 1 } } } ]) `

I'd like to share that this issue closed almost 5 years ago helped me today, meaning that the issue is still present in the latest version.

Basically, the $toString operator doesn't work in the mongodb-grafana plugin, even though it works if you query mongodb directly. But the $convert operator was a working workaround for me. I just wanted to convert a number to string.

Thanks!
